#!/bin/bash
#SBATCH --partition main ### partition name where to run a job. Use ‘main’ unless qos is required. qos partitions ‘rtx3090’ ‘rtx2080’ ‘gtx1080’
#SBATCH --time 6-23:30:00 ### limit the time of job running. Make sure it is not greater than the partition time limit (7 days)!! Format: D-H:MM:SS
#SBATCH --job-name privacy ### name of the job. replace my_job with your desired job name
#SBATCH --output slurm-%J.out ### output log for running job - %J is the job number variable
#SBATCH --gpus=1 ### number of GPUs. Choosing type e.g.: #SBATCH --gpus=gtx_1080:1 , or rtx_2080, or rtx_3090 . Allocating more than 1 requires the IT team’s permission
##SBATCH --tasks=1 # 1 process – use for processing of few programs concurrently in a job (with srun). Use just 1 otherwise

module load cuda/11.2
#module load anaconda
#source activate Privacy
#conda activate Privacy
nvidia-smi -L
#REMAP_TYPE=freq-high 
#REMAP_TYPE=freq-low 
#REMAP_TYPE=random
#DATASET=imdb 
#DATASET=sst2 
#FW=half

# For imdb freq-high/random
# python main.py --frequency_path=/home/reemha/Privacy-Playground/wiki_freq_roberta.pkl --remap_type=$1 --frequency_window=half --dataset=$2 --attacker #--finetune

#for nn attacker
#python main.py --frequency_path=/home/reemha/Privacy-Playground/wiki_freq_roberta.pkl --remap_type=conv --dataset=sst2 --attacker=knn

# For imdb segments
#python main.py --frequency_path=/home/reemha/Privacy-Playground/wiki_freq_roberta.pkl --segment=$3 --remap_type=$1 --frequency_window=half --dataset=$2 --attacker=naive #--finetune

#For generic conv
#python main.py --frequency_path=/home/reemha/Privacy-Playground/wiki_freq_roberta.pkl --remap_type=conv --dataset=$1 --stencil_size=$2 --attacker=knn --remap=all

#high
#python main.py --frequency_path=/home/reemha/Privacy-Playground/wiki_freq_roberta.pkl --remap_type=freq-high --dataset=sst2 --attacker --remap=all --frequency_window=half

#low
# python main.py --frequency_path=/home/reemha/Privacy-Playground/wiki_freq_roberta.pkl --remap_type=freq-low --dataset=imdb --attacker --remap=all --frequency_window=half

#random
python main.py --remap_count=3 --frequency_path=/home/reemha/Privacy-Playground/wiki_freq_roberta.pkl --remap_type=random --dataset=imdb --segment=10  --attacker=naive --remap=all


